# Generated by Django 5.2 on 2025-05-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_reference',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
