# Generated by Django 5.2 on 2025-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_item_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='securetransaction',
            name='item_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
