# Generated by Django 5.2 on 2025-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_securetransaction_item_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapaymentlog',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
