# Generated by Django 5.2 on 2025-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
