# Generated by Django 5.2 on 2025-05-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_item_quantity_transaction_is_bulk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondispute',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondispute',
            name='reason',
            field=models.CharField(choices=[('item_not_received', 'Item not received'), ('item_not_as_described', 'Item not as described'), ('delayed_delivery', 'Delayed delivery'), ('damaged_item', 'Item arrived damaged'), ('wrong_item', 'Wrong item received'), ('other', 'Other')], max_length=50),
        ),
    ]
