# Generated by Django 5.2 on 2025-05-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_disputeevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('self_delivery', 'Self Delivery'), ('courier', 'Courier Service'), ('agent', 'Delivery Agent')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_evidence',
            field=models.FileField(blank=True, null=True, upload_to='shipping_evidence/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, help_text='Registered delivery agent if selected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliveryagent'),
        ),
    ]
