# Generated by Django 5.2 on 2025-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transactionstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
