# Generated by Django 5.2 on 2025-05-11 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_transaction_paid_at_transaction_shipped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaB2CResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result_type', models.IntegerField()),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=255)),
                ('originator_conversation_id', models.CharField(max_length=100)),
                ('conversation_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_response', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
