# Generated by Django 5.2 on 2025-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_premiumsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
