# Generated by Django 5.2 on 2025-05-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_premiumsubscription_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumsubscription',
            old_name='start_date',
            new_name='paid_date',
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='premium_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
