# Generated by Django 5.2 on 2025-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_transaction_arrived_at_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hold_payout',
            field=models.BooleanField(default=False),
        ),
    ]
