# Generated by Django 5.2 on 2025-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_securetransaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='securetransaction',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
