# Generated by Django 5.2 on 2025-06-08 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_securetransaction_shipped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('headquarters_location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='delivery_org_logo/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='deliveryagent',
            old_name='name',
            new_name='region_of_operation',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='email',
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='agent_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization Agent')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='license_document',
            field=models.FileField(null=True, upload_to='delivery_agent_license/'),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='mpesa_phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='police_clearance_certificate',
            field=models.FileField(blank=True, null=True, upload_to='agent_police_clearances/'),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='vehicle_plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('foot', 'On Foot'), ('truck', 'Truck')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Required if registering as organization agent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliveryorganization'),
        ),
    ]
