# Generated by Django 5.2 on 2025-06-11 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_deliveryorganization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
