# Generated by Django 5.2 on 2025-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_deliveryagent_mpesa_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='vehicle_plate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
