# Generated by Django 5.2 on 2025-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_deliveryagent_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securetransaction',
            name='hold_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securetransaction',
            name='is_funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securetransaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
