# Generated by Django 5.2 on 2025-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_securetransaction_hold_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securetransaction',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securetransaction',
            name='hold_payout',
            field=models.BooleanField(default=True),
        ),
    ]
