# Generated by Django 5.2 on 2025-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_securetransaction_funded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securetransaction',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
