# Generated by Django 5.2 on 2025-08-06 20:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_service_transaction_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='delivery_time',
            new_name='delivery_duration',
        ),
        migrations.AddField(
            model_name='service',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV (PDF or DOC)', null=True, upload_to='cvs/', validators=[core.models.Service.validate_cv_file]),
        ),
        migrations.AddField(
            model_name='service',
            name='evidence',
            field=models.ImageField(blank=True, help_text='Upload evidence of service delivery (e.g.certificates, or any supporting documents)', null=True, upload_to='service_evidence/'),
        ),
    ]
