# Generated by Django 5.2 on 2025-08-07 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_delivery_time_service_delivery_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
